main:
  CoM/ZMP_X:
    legends:
      - { key: CM_ZMP_ref,      id: [0] }
      - { key: CM_ZMP_control,  id: [0] }
      - { key: CM_ZMP_planned,  id: [0] }
      - { key: CM_ZMP_measured, id: [0] }
      - { key: CM_CoM_planned,      id: [0] }
      - { key: CM_CoM_controlRobot, id: [0] }
      - { key: CM_CoM_realRobot,    id: [0] }
      #- { key: GT_CoM,              id: [0] }
      #- { key: CM_CoM_real_sub_planned, id: [0] }
      - { key: CM_CoM_MPC,    id: [0] }
      - { key: CM_CoM_real_sub_ZMP_ref, id: [0] }
    bottom_label:
  CoM_X_vel:
    legends:
      - { key: CM_CoM_controlRobot_vel, id: [0] }
      - { key: CM_CoM_realRobot_vel,    id: [0] }
      # - { key: CM_CoM_real_sub_control, id: [0] }
      - { key: CM_CoM_real_sub_planned, id: [0] }
      # - { key: CM_CoM_control_sub_planned, id: [0] }
      - { key: CM_CoM_planned_vel,    id: [0] }
      # - { key: CM_CoM_controlRobot_dcom, id: [0] }
    bottom_label:
  acc/vel_diff:
    legends:
      - { key: CM_DCM_real_sub_planned, id: [0] }
      - { key: CM_ZMP_control_sub_planned, id: [0] }
      - { key: CM_CoM_vel_real_sub_planned,  id: [0] }
      - { key: CM_CoM_planned_acc,  id: [0] }
      - { key: CM_DCM_planned,   id: [0] }
      - { key: CM_DCM_real,      id: [0] }
      - { key: CM_CoM_realRobot_dvel,      id: [0] }
    bottom_label:
  F_x:
    legends:
      - { key: FT_Left_filteredMeasuredWrench,  id: [3] }
      - { key: FT_Right_filteredMeasuredWrench, id: [3] }
      - { key: FT_Left_targetWrench,  id: [3] }
      - { key: FT_Right_targetWrench, id: [3] }
    bottom_label:
#  CoM/ZMP_Y:
#    legends:
#      - { key: CM_ZMP_ref,      id: [1] }
#      - { key: CM_ZMP_control,  id: [1] }
#      - { key: CM_ZMP_planned,  id: [1] }
#      - { key: CM_ZMP_measured, id: [1] }
#      - { key: CM_CoM_real_sub_control, id: [1] }
#      - { key: CM_CoM_controlRobot, id: [1] }
#      - { key: CM_CoM_realRobot,    id: [1] }
#      #- { key: GT_CoM,              id: [1] }
#      #- { key: CM_CoM_planned,      id: [1] }
#    bottom_label:
