main:
  F/M_x:
    legends:
      - { key: FT_Left_filteredMeasuredWrench,  id: [3, 0] }
      - { key: FT_Right_filteredMeasuredWrench, id: [3, 0] }
      - { key: FT_Left_targetWrench,  id: [3, 0] }
      - { key: FT_Right_targetWrench, id: [3, 0] }
    bottom_label:
  F/M_y:
    legends:
      - { key: FT_Left_filteredMeasuredWrench,  id: [4,  1] }
      - { key: FT_Right_filteredMeasuredWrench, id: [4,  1] }
      - { key: FT_Left_targetWrench,  id: [4,  1] }
      - { key: FT_Right_targetWrench, id: [4,  1] }
    bottom_label:
  F/M_z:
    legends:
      - { key: FT_Left_filteredMeasuredWrench,  id: [5, 2] }
      - { key: FT_Right_filteredMeasuredWrench, id: [5, 2] }
      - { key: FT_Left_targetWrench,  id: [5, 2] }
      - { key: FT_Right_targetWrench, id: [5, 2] }
    bottom_label:
